### ISSUE TITLE
Missing vendor folder

### ISSUE THREAD

**Issue by mariofont** [Alvaroctal/foca-deudas#2]
When trying to use this is on my web server I get an error, as it doesn't find the folder "vendor".

**Comment by KevinMarques** [comment]
Try to run `php composer.phar install` from the foca-deudas directory to install latest version of [AltoRouter](http://altorouter.com/usage/install.html), which is a dependency of the project like it's described in Composer.json.

Note that you need to have PHP and [Composer](https://getcomposer.org/doc/00-intro.md) installed in your server.

**Comment by mariofont** [comment]
Thank you. That just solved the issue.
